version: '3.9'
services:
  db:
    container_name: emotion_gpt_api_db
    image: mysql:8.0
    ports:
      - 3030:3306
    volumes:
      - emotion_gpt_api_db_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: emontion_gpt_api_db
      MYSQL_ROOT_PASSWORD: Admin@123

volumes:
  emotion_gpt_api_db_vol: